# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec: build the standalone LeetCode Gym desktop app.

Run from the REPO ROOT (paths below are repo-relative):
    pyinstaller --noconfirm packaging/LeetCodeGym.spec

Produces:
    macOS   -> "dist/LeetCode Gym.app"  (onedir bundle; make_dmg.sh wraps it)
    Windows -> "dist/LeetCode Gym.exe"  (single file)
PyInstaller can't cross-compile: build once on Windows, once on macOS.
"""
import glob
import os
import sys

from PyInstaller.utils.hooks import collect_all

# Anchor every path to the repo root (parent of this spec's folder) so the build
# works regardless of the current directory. SPECPATH is injected by PyInstaller.
REPO = os.path.dirname(SPECPATH)
sys.path.insert(0, REPO)
from tracker import __version__  # noqa: E402  (single source of the version)

APP_NAME = "LeetCode Gym"

# Read-only assets the server serves, as (source, dest-dir-inside-bundle).
# Layout must match tracker.resources.resource_root(): <root>/tracker/static,
# <root>/data/*.json, <root>/tutorials/*.md, <root>/tutorials/assets/**.
datas = [
    (os.path.join(REPO, "tracker", "static"), "tracker/static"),
    (os.path.join(REPO, "data", "problems.json"), "data"),
]
# Generated by the data pipeline (scripts/build_tutorials.py, draft_patterns.py);
# guarded so a checkout from before they existed still builds.
for optional in ("tutorials.json", "patterns.json"):
    p = os.path.join(REPO, "data", optional)
    if os.path.exists(p):
        datas.append((p, "data"))
# The hand-written tutorials + their GIFs. tutorials/anim (the generator, its
# fonts and any venv) is deliberately NOT shipped.
for md in glob.glob(os.path.join(REPO, "tutorials", "*.md")):
    if os.path.basename(md) != "README.md":
        datas.append((md, "tutorials"))
assets = os.path.join(REPO, "tutorials", "assets")
if os.path.isdir(assets):
    datas.append((assets, "tutorials/assets"))

# pywebview picks its GUI backend at runtime (EdgeChromium/pythonnet on Windows,
# WKWebView on macOS), so collect the whole package rather than guess imports.
wv_datas, wv_binaries, wv_hiddenimports = collect_all("webview")
datas += wv_datas

a = Analysis(
    [os.path.join(REPO, "desktop_app.py")],
    pathex=[REPO],
    binaries=wv_binaries,
    datas=datas,
    hiddenimports=wv_hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

# App icon (macOS .icns). Regenerate with: python3 packaging/make_icon.py
ICON = os.path.join(REPO, "packaging", "AppIcon.icns")

if sys.platform == "darwin":
    # macOS -> ONEDIR .app: the Python runtime ships already-unpacked inside the
    # bundle, so launch is fast (no per-start temp extraction) and it behaves like
    # a normal folder-based Mac app. onefile + .app is deprecated by PyInstaller.
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,        # binaries/datas go into COLLECT, not the exe
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,                # windowed app: no terminal window
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        name=APP_NAME,
    )
    app = BUNDLE(
        coll,
        name=f"{APP_NAME}.app",
        icon=ICON,
        bundle_identifier="io.github.guangboyu.leetcode-gym",
        info_plist={
            "CFBundleName": APP_NAME,
            "CFBundleDisplayName": APP_NAME,
            "CFBundleShortVersionString": __version__,
            "CFBundleVersion": __version__,
            "NSHumanReadableCopyright": "MIT License",
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,   # follow Dark Mode
            "LSMinimumSystemVersion": "11.0",           # unified toolbar style
            "LSBackgroundOnly": False,
        },
    )
else:
    # Windows/Linux -> ONEFILE: a single double-click executable ("dist/LeetCode Gym.exe").
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,           # UPX often flags AV false-positives on Windows; skip it
        runtime_tmpdir=None,
        console=False,       # windowed app: no terminal window
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=None,
    )
